//! PyO3 boundary conversions for the generated model types.
//!
//! The PyO3 bindings (`super::bindings`) pass model structs/enums across the
//! FFI boundary **by their bare type** — e.g. a client method returns
//! `PyResult<Catalog>` and accepts `Option<Catalog>` directly. For that to
//! compile and run, each model type must implement PyO3's [`FromPyObject`] /
//! [`IntoPyObject`].
//!
//! Models are generated by `buf` (the buffa or prost plugin), not by trestle, so
//! we can neither add `#[pyclass]` to the struct definition nor a `#[derive]`.
//! Instead we emit the trait impls into a sibling file (`pyo3_impls.rs`) of the
//! generated models module — the orphan rule is satisfied because the model
//! types are *local* to that crate. The impl bodies delegate to
//! [`pythonize`]/`depythonize` over the serde `Serialize`/`Deserialize` impls
//! the model plugin already derives, so nested `MessageField<T>`, `EnumValue<E>`,
//! `Vec<T>`, maps, and scalars are all handled with no per-field codegen.
//!
//! Everything is gated behind `#[cfg(feature = "python")]` so pure-Rust /
//! server-only / WASM consumers never pull `pyo3` into their dependency tree.
//!
//! The emitted code is intentionally **runtime-invariant**: it depends only on
//! the model type names (identical for prost and buffa), not on any runtime
//! wrapper types.
//!
//! [`FromPyObject`]: pyo3::FromPyObject
//! [`IntoPyObject`]: pyo3::IntoPyObject
//! [`pythonize`]: https://docs.rs/pythonize

use std::collections::BTreeSet;

use quote::quote;

use super::super::format_tokens;
use crate::analysis::GenerationPlan;
use crate::parsing::CodeGenMetadata;

/// Generate the `pyo3_impls.rs` content: `FromPyObject` + `IntoPyObject` impls
/// for every message type defined in the project's own packages.
///
/// Returns an empty string when there are no project messages to emit (e.g. a
/// service-less descriptor), so the caller can skip writing the file.
pub(crate) fn generate_pyo3_impls(
    plan: &GenerationPlan,
    metadata: &CodeGenMetadata,
) -> crate::error::Result<String> {
    // The project's own packages, taken straight from the plan's services — the
    // same set whose model modules `generate_models_mod` emits. Message types in
    // any other package (google/gnostic/etc.) are not in our crate and must be
    // skipped (orphan rule + they have no in-crate path).
    let project_packages: BTreeSet<&str> =
        plan.services.iter().map(|s| s.package.as_str()).collect();

    // Emit impls for *every* message in the project's own packages, not just
    // resource-annotated ones: request/response and other non-resource messages
    // (e.g. a custom RPC's `*Status` output) also cross the FFI boundary as bare
    // types. Sort by name for deterministic output.
    let mut names: Vec<&String> = metadata.messages.keys().collect();
    names.sort();

    let mut impls = Vec::new();
    for name in names {
        // `name` is fully qualified, e.g. `.example.catalog.v1.Catalog`. Map it to
        // the in-crate Rust path the model module tree exposes.
        let Some(rust_path) = message_rust_path(name, &project_packages) else {
            continue;
        };
        let ty: syn::Type =
            syn::parse_str(&rust_path).map_err(|e| crate::error::Error::InvalidRustPath {
                path: rust_path.clone(),
                message: name.clone(),
                source: e,
            })?;

        impls.push(quote! {
            impl<'py> ::pyo3::IntoPyObject<'py> for #ty {
                type Target = ::pyo3::PyAny;
                type Output = ::pyo3::Bound<'py, ::pyo3::PyAny>;
                type Error = ::pyo3::PyErr;

                fn into_pyobject(self, py: ::pyo3::Python<'py>) -> ::core::result::Result<Self::Output, Self::Error> {
                    ::pythonize::pythonize(py, &self)
                        .map_err(::core::convert::Into::into)
                }
            }

            impl<'py> ::pyo3::FromPyObject<'py> for #ty {
                fn extract_bound(ob: &::pyo3::Bound<'py, ::pyo3::PyAny>) -> ::pyo3::PyResult<Self> {
                    ::pythonize::depythonize(ob)
                        .map_err(::core::convert::Into::into)
                }
            }
        });
    }

    if impls.is_empty() {
        return Ok(String::new());
    }

    // No file-level inner attributes (`#![..]`) or inner doc comments (`//!`):
    // this file is mounted via `#[cfg(feature = "python")] mod pyo3_impls;` in the
    // generated `mod.rs` (which already gates it on the feature), and keeping it
    // free of inner attributes also lets consumers `include!` it directly.
    let tokens = quote! {
        // PyO3 boundary conversions for the generated model types.
        //
        // `FromPyObject`/`IntoPyObject` are implemented via `pythonize` over the
        // models' serde derives, so model values cross the PyO3 boundary as plain
        // Python objects (dicts / lists / scalars). Mounted under the `python`
        // feature; see the model module's `mod.rs`.

        #(#impls)*
    };

    format_tokens(tokens)
}

/// Map a fully-qualified proto message name to its in-crate Rust path, as exposed
/// by the model module tree `generate_models_mod` emits.
///
/// `pyo3_impls.rs` is a sibling of the per-package model modules inside the models
/// subdir, so the path is `super::<svc_seg>::<ver_seg>::<...nested>::<Name>` where
/// `(svc_seg, ver_seg)` are the second-to-last and last segments of the owning
/// package — exactly the module nesting `generate_models_mod` produces.
///
/// Returns `None` for messages outside the project's own packages (e.g. imported
/// google/gnostic types), which have no in-crate path and must be skipped.
fn message_rust_path(fq_name: &str, project_packages: &BTreeSet<&str>) -> Option<String> {
    let stripped = fq_name.strip_prefix('.').unwrap_or(fq_name);

    // Find the owning project package: the longest one that is a dot-segment
    // prefix of the message name.
    let package = project_packages
        .iter()
        .filter(|pkg| {
            stripped == **pkg
                || stripped
                    .strip_prefix(**pkg)
                    .is_some_and(|rest| rest.starts_with('.'))
        })
        .max_by_key(|pkg| pkg.len())?;

    // Segments after the package: the message name plus any nesting parents.
    let remainder = stripped.strip_prefix(package)?.trim_start_matches('.');
    if remainder.is_empty() {
        return None;
    }

    // Module nesting for the package mirrors `generate_models_mod::mod_segments`:
    // second-to-last and last package segments (e.g. `example.catalog.v1` →
    // `catalog::v1`, `demo.v1` → `demo::v1`).
    let pkg_parts: Vec<&str> = package.split('.').collect();
    let module_path = if pkg_parts.len() >= 2 {
        format!(
            "{}::{}",
            pkg_parts[pkg_parts.len() - 2],
            pkg_parts[pkg_parts.len() - 1]
        )
    } else {
        // Single-segment package: `generate_models_mod` falls back to
        // `<base_path>::v1`, but a single-segment proto package is degenerate
        // here; use the one segment as-is.
        pkg_parts[0].to_string()
    };

    let type_path = remainder.replace('.', "::");
    Some(format!("super::{}::{}", module_path, type_path))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pkgs(list: &[&'static str]) -> BTreeSet<&'static str> {
        list.iter().copied().collect()
    }

    #[test]
    fn three_segment_package_maps_to_service_version_module() {
        // Matches the labels.rs convention and the golden tree.
        let p = pkgs(&["example.catalog.v1"]);
        assert_eq!(
            message_rust_path(".example.catalog.v1.Catalog", &p).as_deref(),
            Some("super::catalog::v1::Catalog")
        );
    }

    #[test]
    fn two_segment_package_keeps_first_segment_as_module() {
        // The case the buffa_e2e fixture exercises: `demo.v1` nests as `demo::v1`,
        // NOT `v1` — second-to-last + last segments.
        let p = pkgs(&["demo.v1"]);
        assert_eq!(
            message_rust_path(".demo.v1.Widget", &p).as_deref(),
            Some("super::demo::v1::Widget")
        );
    }

    #[test]
    fn nested_message_keeps_parent_in_path() {
        let p = pkgs(&["example.catalog.v1"]);
        assert_eq!(
            message_rust_path(".example.catalog.v1.Catalog.Nested", &p).as_deref(),
            Some("super::catalog::v1::Catalog::Nested")
        );
    }

    #[test]
    fn foreign_package_is_skipped() {
        let p = pkgs(&["example.catalog.v1"]);
        assert_eq!(message_rust_path(".google.protobuf.Any", &p), None);
    }

    #[test]
    fn longest_matching_package_wins() {
        // A package and a sub-package both registered: the message belongs to the
        // more specific one.
        let p = pkgs(&["example.catalog.v1", "example.catalog.v1.sub"]);
        assert_eq!(
            message_rust_path(".example.catalog.v1.sub.Thing", &p).as_deref(),
            Some("super::v1::sub::Thing")
        );
    }
}
