//! Shared types for the golden-path-app app. The `models` module is populated
//! by `trestle generate` from `proto/golden_path_app/v1/*.proto`.

pub mod models {
    //! Generated model types (proto types generated by buf under `_gen/`).
    //! Re-exported here so consumers import from a stable path.
    include!("models/mod.rs");
}
