#!/usr/bin/env bash
# Render a Homebrew formula for a prebuilt CLI released to GitHub Releases.
#
# Standalone + parameterized on purpose: the CI job in release-plz.yml calls it,
# but it takes everything it needs as flags/env so it can be lifted into a shared
# `open-lakehouse/.github` reusable workflow unchanged when a second org binary
# needs a formula (see docs/architecture + CONTRIBUTING). No release-plz- or
# trestle-specific logic lives here.
#
# It emits the formula on stdout. The four per-target SHA-256 checksums are read
# from `<checksums-dir>/trestle-<target>.tar.gz.sha256` — the exact sidecar files
# `release-binaries.yml` uploads to each release (via upload-rust-binary-action
# `checksum: sha256`). Each sidecar is `<hash>  <filename>`; we take field 1.
#
# Usage:
#   gen-homebrew-formula.sh \
#     --tool trestle \
#     --crate olai-trestle \
#     --version 0.0.6 \
#     --repo open-lakehouse/trestle \
#     --tag-prefix olai-trestle-v \
#     --checksums-dir ./checksums \
#     --class Trestle \
#     --desc "Unified CLI for proto-driven code generation and full-project scaffolding" \
#     --homepage https://github.com/open-lakehouse/trestle
#
# Every flag is required except --tag-prefix (defaults to "<crate>-v") and
# --class (defaults to the capitalized --tool).
set -euo pipefail

tool="" crate="" version="" repo="" tag_prefix="" formula_class="" desc="" homepage="" checksums_dir=""

while [ $# -gt 0 ]; do
  case "$1" in
    --tool) tool="$2"; shift 2 ;;
    --crate) crate="$2"; shift 2 ;;
    --version) version="$2"; shift 2 ;;
    --repo) repo="$2"; shift 2 ;;
    --tag-prefix) tag_prefix="$2"; shift 2 ;;
    --class) formula_class="$2"; shift 2 ;;
    --desc) desc="$2"; shift 2 ;;
    --homepage) homepage="$2"; shift 2 ;;
    --checksums-dir) checksums_dir="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

die() { echo "gen-homebrew-formula: $1" >&2; exit 2; }
[ -n "$tool" ] || die "--tool is required"
[ -n "$crate" ] || die "--crate is required"
[ -n "$version" ] || die "--version is required"
[ -n "$repo" ] || die "--repo is required"
[ -n "$desc" ] || die "--desc is required"
[ -n "$homepage" ] || die "--homepage is required"
[ -n "$checksums_dir" ] || die "--checksums-dir is required"
[ -n "$tag_prefix" ] || tag_prefix="${crate}-v"
# Default class name: capitalize the first letter of --tool (Homebrew wants the
# formula class to be the CamelCased file stem, e.g. trestle.rb -> Trestle).
if [ -z "$formula_class" ]; then
  formula_class="$(printf '%s' "${tool:0:1}" | tr '[:lower:]' '[:upper:]')${tool:1}"
fi

# Read the SHA-256 for a given Rust target's archive from its .sha256 sidecar.
# Resolve a target's .sha256 sidecar file, or print nothing if absent.
#   upload-rust-binary-action names the checksum after the archive *stem*
#   (`trestle-<target>.sha256`), not `<archive>.sha256`. Accept either name so the
#   generator keeps working if the action's convention ever changes.
sha_file() {
  local target="$1"
  local f="${checksums_dir}/${tool}-${target}.sha256"
  [ -f "$f" ] || f="${checksums_dir}/${tool}-${target}.tar.gz.sha256"
  if [ -f "$f" ]; then printf '%s' "$f"; fi
  return 0 # never fail: absence is signalled by empty output, not exit status
}

# Read the SHA-256 for a target from its sidecar ("<hash>  <filename>").
sha_for() { awk '{print $1; exit}' "$1"; }

# Emit an `on_arm`/`on_intel` sub-block for one target IFF its checksum is
# present. Auto-detecting keeps a single code path working both before and after
# a target is added to release-binaries.yml (e.g. x86_64-apple-darwin, which
# older releases predate) — a target with no published archive is simply omitted
# rather than producing a formula that 404s on \`brew install\`.
arch_block() {
  local arm_kw="$1" target="$2" # e.g. "on_arm" / "on_intel", rust target triple
  local f; f="$(sha_file "$target")"
  [ -n "$f" ] || return 0
  cat <<EOF
    ${arm_kw} do
      url "${base_url}/${tool}-${target}.tar.gz"
      sha256 "$(sha_for "$f")"
    end
EOF
}

base_url="https://github.com/${repo}/releases/download/${tag_prefix}${version}"

# At minimum we require the two Linux targets + arm64 macOS (shipped since the
# first binary release); x86_64 macOS is optional (added later).
for req in aarch64-apple-darwin aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu; do
  [ -n "$(sha_file "$req")" ] || die "missing required checksum for ${tool}-${req} in ${checksums_dir}"
done

# Emit the formula directly (calling arch_block inline preserves its newlines;
# capturing into a var via $() would strip trailing newlines and glue blocks).
cat <<EOF
# typed: strict
# frozen_string_literal: true

# This file is generated by scripts/gen-homebrew-formula.sh on each ${crate}
# release. Do not edit by hand — edits will be overwritten on the next release.
class ${formula_class} < Formula
  desc "${desc}"
  homepage "${homepage}"
  license "Apache-2.0"
  # No explicit \`version\`: Homebrew scans it from the \`${tag_prefix}<version>\`
  # segment of the download URLs (an explicit line trips FormulaAudit/Version as
  # redundant).

  # No \`livecheck\` block on purpose: this is our own tap, and the
  # \`bump-homebrew\` CI job regenerates this formula on every ${crate} release,
  # so there is nothing for Homebrew's autobump bot to discover. (A livecheck
  # here would also need a per-crate tag filter — other workspace crates tag
  # under different prefixes — which \`url :stable\` cannot express.)

  on_macos do
EOF
arch_block on_arm aarch64-apple-darwin
arch_block on_intel x86_64-apple-darwin
cat <<EOF
  end

  on_linux do
EOF
arch_block on_arm aarch64-unknown-linux-gnu
arch_block on_intel x86_64-unknown-linux-gnu
cat <<EOF
  end

  # release-binaries.yml packages with \`leading-dir: true\`, so every archive
  # unpacks to a single \`${tool}-<target>/\` directory containing the binary.
  # Homebrew does not strip that dir, so glob for the binary wherever it landed
  # rather than hard-coding the per-platform target triple.
  def install
    bin.install Dir["**/${tool}"].first
  end

  test do
    assert_match "${tool}", shell_output("#{bin}/${tool} --version")
  end
end
EOF
