// @generated by buffa-codegen. DO NOT EDIT.

#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct Greeting {
    /// Server-assigned. Format: `greetings/{uuid}`.
    ///
    /// Field 1: `name`
    #[serde(
        rename = "name",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub name: ::buffa::alloc::string::String,
    /// Who is being greeted.
    ///
    /// Field 2: `recipient`
    #[serde(
        rename = "recipient",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub recipient: ::buffa::alloc::string::String,
    /// The rendered greeting, e.g. "hello, world!".
    ///
    /// Field 3: `message`
    #[serde(
        rename = "message",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub message: ::buffa::alloc::string::String,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for Greeting {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Greeting")
            .field("name", &self.name)
            .field("recipient", &self.recipient)
            .field("message", &self.message)
            .finish()
    }
}
impl Greeting {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/golden_path_app.v1.Greeting";
}
impl ::buffa::DefaultInstance for Greeting {
    fn default_instance() -> &'static Self {
        static VALUE: ::buffa::__private::OnceBox<Greeting> = ::buffa::__private::OnceBox::new();
        VALUE.get_or_init(|| ::buffa::alloc::boxed::Box::new(Self::default()))
    }
}
impl ::buffa::MessageName for Greeting {
    const PACKAGE: &'static str = "golden_path_app.v1";
    const NAME: &'static str = "Greeting";
    const FULL_NAME: &'static str = "golden_path_app.v1.Greeting";
    const TYPE_URL: &'static str = "type.googleapis.com/golden_path_app.v1.Greeting";
}
impl ::buffa::Message for Greeting {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.name.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.name) as u32;
        }
        if !self.recipient.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.recipient) as u32;
        }
        if !self.message.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.message) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.name.is_empty() {
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.name, buf);
        }
        if !self.recipient.is_empty() {
            ::buffa::encoding::Tag::new(
                    2u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.recipient, buf);
        }
        if !self.message.is_empty() {
            ::buffa::encoding::Tag::new(
                    3u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.message, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 1u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.name, buf)?;
            }
            2u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 2u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.recipient, buf)?;
            }
            3u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 3u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.message, buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, depth)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.name.clear();
        self.recipient.clear();
        self.message.clear();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for Greeting {
    const PROTO_FQN: &'static str = "golden_path_app.v1.Greeting";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for Greeting {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __GREETING_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/golden_path_app.v1.Greeting",
    to_json: ::buffa::type_registry::any_to_json::<Greeting>,
    from_json: ::buffa::type_registry::any_from_json::<Greeting>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct CreateGreetingRequest {
    /// Field 1: `greeting`
    #[serde(
        rename = "greeting",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub greeting: ::buffa::MessageField<Greeting>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for CreateGreetingRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("CreateGreetingRequest")
            .field("greeting", &self.greeting)
            .finish()
    }
}
impl CreateGreetingRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/golden_path_app.v1.CreateGreetingRequest";
}
impl ::buffa::DefaultInstance for CreateGreetingRequest {
    fn default_instance() -> &'static Self {
        static VALUE: ::buffa::__private::OnceBox<CreateGreetingRequest> = ::buffa::__private::OnceBox::new();
        VALUE.get_or_init(|| ::buffa::alloc::boxed::Box::new(Self::default()))
    }
}
impl ::buffa::MessageName for CreateGreetingRequest {
    const PACKAGE: &'static str = "golden_path_app.v1";
    const NAME: &'static str = "CreateGreetingRequest";
    const FULL_NAME: &'static str = "golden_path_app.v1.CreateGreetingRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/golden_path_app.v1.CreateGreetingRequest";
}
impl ::buffa::Message for CreateGreetingRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.greeting.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.greeting.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.greeting.is_set() {
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__cache.consume_next() as u64, buf);
            self.greeting.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 1u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::Message::merge_length_delimited(
                    self.greeting.get_or_insert_default(),
                    buf,
                    depth,
                )?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, depth)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.greeting = ::buffa::MessageField::none();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for CreateGreetingRequest {
    const PROTO_FQN: &'static str = "golden_path_app.v1.CreateGreetingRequest";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for CreateGreetingRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __CREATE_GREETING_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/golden_path_app.v1.CreateGreetingRequest",
    to_json: ::buffa::type_registry::any_to_json::<CreateGreetingRequest>,
    from_json: ::buffa::type_registry::any_from_json::<CreateGreetingRequest>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct GetGreetingRequest {
    /// Field 1: `name`
    #[serde(
        rename = "name",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub name: ::buffa::alloc::string::String,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for GetGreetingRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("GetGreetingRequest").field("name", &self.name).finish()
    }
}
impl GetGreetingRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/golden_path_app.v1.GetGreetingRequest";
}
impl ::buffa::DefaultInstance for GetGreetingRequest {
    fn default_instance() -> &'static Self {
        static VALUE: ::buffa::__private::OnceBox<GetGreetingRequest> = ::buffa::__private::OnceBox::new();
        VALUE.get_or_init(|| ::buffa::alloc::boxed::Box::new(Self::default()))
    }
}
impl ::buffa::MessageName for GetGreetingRequest {
    const PACKAGE: &'static str = "golden_path_app.v1";
    const NAME: &'static str = "GetGreetingRequest";
    const FULL_NAME: &'static str = "golden_path_app.v1.GetGreetingRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/golden_path_app.v1.GetGreetingRequest";
}
impl ::buffa::Message for GetGreetingRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.name.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.name) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.name.is_empty() {
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.name, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 1u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.name, buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, depth)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.name.clear();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for GetGreetingRequest {
    const PROTO_FQN: &'static str = "golden_path_app.v1.GetGreetingRequest";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for GetGreetingRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __GET_GREETING_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/golden_path_app.v1.GetGreetingRequest",
    to_json: ::buffa::type_registry::any_to_json::<GetGreetingRequest>,
    from_json: ::buffa::type_registry::any_from_json::<GetGreetingRequest>,
    is_wkt: false,
};
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Clone, Debug, Default)]
        pub struct GreetingView<'a> {
            /// Server-assigned. Format: `greetings/{uuid}`.
            ///
            /// Field 1: `name`
            pub name: &'a str,
            /// Who is being greeted.
            ///
            /// Field 2: `recipient`
            pub recipient: &'a str,
            /// The rendered greeting, e.g. "hello, world!".
            ///
            /// Field 3: `message`
            pub message: &'a str,
            pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
        }
        impl<'a> GreetingView<'a> {
            /// Decode from `buf`, enforcing a recursion depth limit for nested messages.
            ///
            /// Called by [`::buffa::MessageView::decode_view`] with [`::buffa::RECURSION_LIMIT`]
            /// and by generated sub-message decode arms with `depth - 1`.
            ///
            /// **Not part of the public API.** Named with a leading underscore to
            /// signal that it is for generated-code use only.
            #[doc(hidden)]
            pub fn _decode_depth(
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                let mut view = Self::default();
                view._merge_into_view(buf, depth)?;
                ::core::result::Result::Ok(view)
            }
            /// Merge fields from `buf` into this view (proto merge semantics).
            ///
            /// Repeated fields append; singular fields last-wins; singular
            /// MESSAGE fields merge recursively. Used by sub-message decode
            /// arms when the same field appears multiple times on the wire.
            ///
            /// **Not part of the public API.**
            #[doc(hidden)]
            pub fn _merge_into_view(
                &mut self,
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<(), ::buffa::DecodeError> {
                let _ = depth;
                #[allow(unused_variables)]
                let view = self;
                let mut cur: &'a [u8] = buf;
                while !cur.is_empty() {
                    let before_tag = cur;
                    let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
                    match tag.field_number() {
                        1u32 => {
                            if tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 1u32,
                                    expected: 2u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            view.name = ::buffa::types::borrow_str(&mut cur)?;
                        }
                        2u32 => {
                            if tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 2u32,
                                    expected: 2u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            view.recipient = ::buffa::types::borrow_str(&mut cur)?;
                        }
                        3u32 => {
                            if tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 3u32,
                                    expected: 2u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            view.message = ::buffa::types::borrow_str(&mut cur)?;
                        }
                        _ => {
                            ::buffa::encoding::skip_field_depth(tag, &mut cur, depth)?;
                            let span_len = before_tag.len() - cur.len();
                            view.__buffa_unknown_fields
                                .push_raw(&before_tag[..span_len]);
                        }
                    }
                }
                ::core::result::Result::Ok(())
            }
        }
        impl<'a> ::buffa::MessageView<'a> for GreetingView<'a> {
            type Owned = super::super::Greeting;
            fn decode_view(
                buf: &'a [u8],
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                Self::_decode_depth(buf, ::buffa::RECURSION_LIMIT)
            }
            fn decode_view_with_limit(
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                Self::_decode_depth(buf, depth)
            }
            fn to_owned_message(&self) -> super::super::Greeting {
                self.to_owned_from_source(None)
            }
            #[allow(clippy::useless_conversion, clippy::needless_update)]
            fn to_owned_from_source(
                &self,
                __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
            ) -> super::super::Greeting {
                #[allow(unused_imports)]
                use ::buffa::alloc::string::ToString as _;
                let _ = __buffa_src;
                super::super::Greeting {
                    name: self.name.to_string(),
                    recipient: self.recipient.to_string(),
                    message: self.message.to_string(),
                    __buffa_unknown_fields: self
                        .__buffa_unknown_fields
                        .to_owned()
                        .unwrap_or_default()
                        .into(),
                    ..::core::default::Default::default()
                }
            }
        }
        impl<'a> ::buffa::ViewEncode<'a> for GreetingView<'a> {
            #[allow(clippy::needless_borrow, clippy::let_and_return)]
            fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
                #[allow(unused_imports)]
                use ::buffa::Enumeration as _;
                let mut size = 0u32;
                if !self.name.is_empty() {
                    size += 1u32 + ::buffa::types::string_encoded_len(&self.name) as u32;
                }
                if !self.recipient.is_empty() {
                    size
                        += 1u32
                            + ::buffa::types::string_encoded_len(&self.recipient) as u32;
                }
                if !self.message.is_empty() {
                    size
                        += 1u32
                            + ::buffa::types::string_encoded_len(&self.message) as u32;
                }
                size += self.__buffa_unknown_fields.encoded_len() as u32;
                size
            }
            #[allow(clippy::needless_borrow)]
            fn write_to(
                &self,
                _cache: &mut ::buffa::SizeCache,
                buf: &mut impl ::buffa::bytes::BufMut,
            ) {
                #[allow(unused_imports)]
                use ::buffa::Enumeration as _;
                if !self.name.is_empty() {
                    ::buffa::encoding::Tag::new(
                            1u32,
                            ::buffa::encoding::WireType::LengthDelimited,
                        )
                        .encode(buf);
                    ::buffa::types::encode_string(&self.name, buf);
                }
                if !self.recipient.is_empty() {
                    ::buffa::encoding::Tag::new(
                            2u32,
                            ::buffa::encoding::WireType::LengthDelimited,
                        )
                        .encode(buf);
                    ::buffa::types::encode_string(&self.recipient, buf);
                }
                if !self.message.is_empty() {
                    ::buffa::encoding::Tag::new(
                            3u32,
                            ::buffa::encoding::WireType::LengthDelimited,
                        )
                        .encode(buf);
                    ::buffa::types::encode_string(&self.message, buf);
                }
                self.__buffa_unknown_fields.write_to(buf);
            }
        }
        /// Serializes this view as protobuf JSON.
        ///
        /// Implicit-presence fields with default values are omitted, `required`
        /// fields are always emitted, explicit-presence (`optional`) fields are
        /// emitted only when set, bytes fields are base64-encoded, and enum
        /// values are their proto name strings.
        ///
        /// This impl uses `serialize_map(None)` because the number of emitted
        /// fields depends on default-omission rules; serializers that require
        /// known map lengths (e.g. `bincode`) will return a runtime error.
        /// Use the owned message type for those formats.
        impl<'__a> ::serde::Serialize for GreetingView<'__a> {
            fn serialize<__S: ::serde::Serializer>(
                &self,
                __s: __S,
            ) -> ::core::result::Result<__S::Ok, __S::Error> {
                use ::serde::ser::SerializeMap as _;
                let mut __map = __s.serialize_map(::core::option::Option::None)?;
                if !::buffa::json_helpers::skip_if::is_empty_str(self.name) {
                    __map.serialize_entry("name", self.name)?;
                }
                if !::buffa::json_helpers::skip_if::is_empty_str(self.recipient) {
                    __map.serialize_entry("recipient", self.recipient)?;
                }
                if !::buffa::json_helpers::skip_if::is_empty_str(self.message) {
                    __map.serialize_entry("message", self.message)?;
                }
                __map.end()
            }
        }
        impl<'a> ::buffa::MessageName for GreetingView<'a> {
            const PACKAGE: &'static str = "golden_path_app.v1";
            const NAME: &'static str = "Greeting";
            const FULL_NAME: &'static str = "golden_path_app.v1.Greeting";
            const TYPE_URL: &'static str = "type.googleapis.com/golden_path_app.v1.Greeting";
        }
        impl<'v> ::buffa::DefaultViewInstance for GreetingView<'v> {
            fn default_view_instance<'a>() -> &'a Self
            where
                Self: 'a,
            {
                static VALUE: ::buffa::__private::OnceBox<GreetingView<'static>> = ::buffa::__private::OnceBox::new();
                VALUE
                    .get_or_init(|| ::buffa::alloc::boxed::Box::new(
                        <GreetingView<'static>>::default(),
                    ))
            }
        }
        impl ::buffa::ViewReborrow for GreetingView<'static> {
            type Reborrowed<'b> = GreetingView<'b>;
            fn reborrow<'b>(this: &'b Self) -> &'b Self::Reborrowed<'b> {
                this
            }
        }
        /** Self-contained, `'static` owned view of a `Greeting` message.

 Wraps [`::buffa::OwnedView`]`<`[`GreetingView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`GreetingView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
        #[derive(Clone, Debug)]
        pub struct GreetingOwnedView(::buffa::OwnedView<GreetingView<'static>>);
        impl GreetingOwnedView {
            /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
            ///
            /// The view borrows directly from the buffer's data; the buffer is
            /// retained inside the returned handle.
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
            /// protobuf data.
            pub fn decode(
                bytes: ::buffa::bytes::Bytes,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    GreetingOwnedView(::buffa::OwnedView::decode(bytes)?),
                )
            }
            /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
            /// max message size).
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
            /// exceeds the configured limits.
            pub fn decode_with_options(
                bytes: ::buffa::bytes::Bytes,
                opts: &::buffa::DecodeOptions,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    GreetingOwnedView(
                        ::buffa::OwnedView::decode_with_options(bytes, opts)?,
                    ),
                )
            }
            /// Build from an owned message via an encode → decode round-trip.
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
            /// somehow invalid (should not happen for well-formed messages).
            pub fn from_owned(
                msg: &super::super::Greeting,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    GreetingOwnedView(::buffa::OwnedView::from_owned(msg)?),
                )
            }
            /// Borrow the full [`GreetingView`] with its lifetime tied to `&self`.
            #[must_use]
            pub fn view(&self) -> &GreetingView<'_> {
                self.0.reborrow()
            }
            /// Convert to the owned message type.
            #[must_use]
            pub fn to_owned_message(&self) -> super::super::Greeting {
                self.0.to_owned_message()
            }
            /// The underlying bytes buffer.
            #[must_use]
            pub fn bytes(&self) -> &::buffa::bytes::Bytes {
                self.0.bytes()
            }
            /// Consume the handle, returning the underlying bytes buffer.
            #[must_use]
            pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
                self.0.into_bytes()
            }
            /// Server-assigned. Format: `greetings/{uuid}`.
            ///
            /// Field 1: `name`
            #[must_use]
            pub fn name(&self) -> &'_ str {
                self.0.reborrow().name
            }
            /// Who is being greeted.
            ///
            /// Field 2: `recipient`
            #[must_use]
            pub fn recipient(&self) -> &'_ str {
                self.0.reborrow().recipient
            }
            /// The rendered greeting, e.g. "hello, world!".
            ///
            /// Field 3: `message`
            #[must_use]
            pub fn message(&self) -> &'_ str {
                self.0.reborrow().message
            }
        }
        impl ::core::convert::From<::buffa::OwnedView<GreetingView<'static>>>
        for GreetingOwnedView {
            fn from(inner: ::buffa::OwnedView<GreetingView<'static>>) -> Self {
                GreetingOwnedView(inner)
            }
        }
        impl ::core::convert::From<GreetingOwnedView>
        for ::buffa::OwnedView<GreetingView<'static>> {
            fn from(wrapper: GreetingOwnedView) -> Self {
                wrapper.0
            }
        }
        impl ::core::convert::AsRef<::buffa::OwnedView<GreetingView<'static>>>
        for GreetingOwnedView {
            fn as_ref(&self) -> &::buffa::OwnedView<GreetingView<'static>> {
                &self.0
            }
        }
        impl ::buffa::HasMessageView for super::super::Greeting {
            type View<'a> = GreetingView<'a>;
            type ViewHandle = GreetingOwnedView;
        }
        impl ::serde::Serialize for GreetingOwnedView {
            fn serialize<__S: ::serde::Serializer>(
                &self,
                __s: __S,
            ) -> ::core::result::Result<__S::Ok, __S::Error> {
                ::serde::Serialize::serialize(&self.0, __s)
            }
        }
        #[derive(Clone, Debug, Default)]
        pub struct CreateGreetingRequestView<'a> {
            /// Field 1: `greeting`
            pub greeting: ::buffa::MessageFieldView<
                super::super::__buffa::view::GreetingView<'a>,
            >,
            pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
        }
        impl<'a> CreateGreetingRequestView<'a> {
            /// Decode from `buf`, enforcing a recursion depth limit for nested messages.
            ///
            /// Called by [`::buffa::MessageView::decode_view`] with [`::buffa::RECURSION_LIMIT`]
            /// and by generated sub-message decode arms with `depth - 1`.
            ///
            /// **Not part of the public API.** Named with a leading underscore to
            /// signal that it is for generated-code use only.
            #[doc(hidden)]
            pub fn _decode_depth(
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                let mut view = Self::default();
                view._merge_into_view(buf, depth)?;
                ::core::result::Result::Ok(view)
            }
            /// Merge fields from `buf` into this view (proto merge semantics).
            ///
            /// Repeated fields append; singular fields last-wins; singular
            /// MESSAGE fields merge recursively. Used by sub-message decode
            /// arms when the same field appears multiple times on the wire.
            ///
            /// **Not part of the public API.**
            #[doc(hidden)]
            pub fn _merge_into_view(
                &mut self,
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<(), ::buffa::DecodeError> {
                let _ = depth;
                #[allow(unused_variables)]
                let view = self;
                let mut cur: &'a [u8] = buf;
                while !cur.is_empty() {
                    let before_tag = cur;
                    let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
                    match tag.field_number() {
                        1u32 => {
                            if tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 1u32,
                                    expected: 2u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            if depth == 0 {
                                return Err(::buffa::DecodeError::RecursionLimitExceeded);
                            }
                            let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                            match view.greeting.as_mut() {
                                Some(existing) => existing._merge_into_view(sub, depth - 1)?,
                                None => {
                                    view.greeting = ::buffa::MessageFieldView::set(
                                        super::super::__buffa::view::GreetingView::_decode_depth(
                                            sub,
                                            depth - 1,
                                        )?,
                                    );
                                }
                            }
                        }
                        _ => {
                            ::buffa::encoding::skip_field_depth(tag, &mut cur, depth)?;
                            let span_len = before_tag.len() - cur.len();
                            view.__buffa_unknown_fields
                                .push_raw(&before_tag[..span_len]);
                        }
                    }
                }
                ::core::result::Result::Ok(())
            }
        }
        impl<'a> ::buffa::MessageView<'a> for CreateGreetingRequestView<'a> {
            type Owned = super::super::CreateGreetingRequest;
            fn decode_view(
                buf: &'a [u8],
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                Self::_decode_depth(buf, ::buffa::RECURSION_LIMIT)
            }
            fn decode_view_with_limit(
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                Self::_decode_depth(buf, depth)
            }
            fn to_owned_message(&self) -> super::super::CreateGreetingRequest {
                self.to_owned_from_source(None)
            }
            #[allow(clippy::useless_conversion, clippy::needless_update)]
            fn to_owned_from_source(
                &self,
                __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
            ) -> super::super::CreateGreetingRequest {
                #[allow(unused_imports)]
                use ::buffa::alloc::string::ToString as _;
                let _ = __buffa_src;
                super::super::CreateGreetingRequest {
                    greeting: match self.greeting.as_option() {
                        Some(v) => {
                            ::buffa::MessageField::<
                                super::super::Greeting,
                            >::some(v.to_owned_from_source(__buffa_src))
                        }
                        None => ::buffa::MessageField::none(),
                    },
                    __buffa_unknown_fields: self
                        .__buffa_unknown_fields
                        .to_owned()
                        .unwrap_or_default()
                        .into(),
                    ..::core::default::Default::default()
                }
            }
        }
        impl<'a> ::buffa::ViewEncode<'a> for CreateGreetingRequestView<'a> {
            #[allow(clippy::needless_borrow, clippy::let_and_return)]
            fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
                #[allow(unused_imports)]
                use ::buffa::Enumeration as _;
                let mut size = 0u32;
                if self.greeting.is_set() {
                    let __slot = __cache.reserve();
                    let inner_size = self.greeting.compute_size(__cache);
                    __cache.set(__slot, inner_size);
                    size
                        += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                            + inner_size;
                }
                size += self.__buffa_unknown_fields.encoded_len() as u32;
                size
            }
            #[allow(clippy::needless_borrow)]
            fn write_to(
                &self,
                __cache: &mut ::buffa::SizeCache,
                buf: &mut impl ::buffa::bytes::BufMut,
            ) {
                #[allow(unused_imports)]
                use ::buffa::Enumeration as _;
                if self.greeting.is_set() {
                    ::buffa::encoding::Tag::new(
                            1u32,
                            ::buffa::encoding::WireType::LengthDelimited,
                        )
                        .encode(buf);
                    ::buffa::encoding::encode_varint(__cache.consume_next() as u64, buf);
                    self.greeting.write_to(__cache, buf);
                }
                self.__buffa_unknown_fields.write_to(buf);
            }
        }
        /// Serializes this view as protobuf JSON.
        ///
        /// Implicit-presence fields with default values are omitted, `required`
        /// fields are always emitted, explicit-presence (`optional`) fields are
        /// emitted only when set, bytes fields are base64-encoded, and enum
        /// values are their proto name strings.
        ///
        /// This impl uses `serialize_map(None)` because the number of emitted
        /// fields depends on default-omission rules; serializers that require
        /// known map lengths (e.g. `bincode`) will return a runtime error.
        /// Use the owned message type for those formats.
        impl<'__a> ::serde::Serialize for CreateGreetingRequestView<'__a> {
            fn serialize<__S: ::serde::Serializer>(
                &self,
                __s: __S,
            ) -> ::core::result::Result<__S::Ok, __S::Error> {
                use ::serde::ser::SerializeMap as _;
                let mut __map = __s.serialize_map(::core::option::Option::None)?;
                {
                    if let ::core::option::Option::Some(__v) = self.greeting.as_option()
                    {
                        __map.serialize_entry("greeting", __v)?;
                    }
                }
                __map.end()
            }
        }
        impl<'a> ::buffa::MessageName for CreateGreetingRequestView<'a> {
            const PACKAGE: &'static str = "golden_path_app.v1";
            const NAME: &'static str = "CreateGreetingRequest";
            const FULL_NAME: &'static str = "golden_path_app.v1.CreateGreetingRequest";
            const TYPE_URL: &'static str = "type.googleapis.com/golden_path_app.v1.CreateGreetingRequest";
        }
        impl<'v> ::buffa::DefaultViewInstance for CreateGreetingRequestView<'v> {
            fn default_view_instance<'a>() -> &'a Self
            where
                Self: 'a,
            {
                static VALUE: ::buffa::__private::OnceBox<
                    CreateGreetingRequestView<'static>,
                > = ::buffa::__private::OnceBox::new();
                VALUE
                    .get_or_init(|| ::buffa::alloc::boxed::Box::new(
                        <CreateGreetingRequestView<'static>>::default(),
                    ))
            }
        }
        impl ::buffa::ViewReborrow for CreateGreetingRequestView<'static> {
            type Reborrowed<'b> = CreateGreetingRequestView<'b>;
            fn reborrow<'b>(this: &'b Self) -> &'b Self::Reborrowed<'b> {
                this
            }
        }
        /** Self-contained, `'static` owned view of a `CreateGreetingRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`CreateGreetingRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`CreateGreetingRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
        #[derive(Clone, Debug)]
        pub struct CreateGreetingRequestOwnedView(
            ::buffa::OwnedView<CreateGreetingRequestView<'static>>,
        );
        impl CreateGreetingRequestOwnedView {
            /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
            ///
            /// The view borrows directly from the buffer's data; the buffer is
            /// retained inside the returned handle.
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
            /// protobuf data.
            pub fn decode(
                bytes: ::buffa::bytes::Bytes,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    CreateGreetingRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
                )
            }
            /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
            /// max message size).
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
            /// exceeds the configured limits.
            pub fn decode_with_options(
                bytes: ::buffa::bytes::Bytes,
                opts: &::buffa::DecodeOptions,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    CreateGreetingRequestOwnedView(
                        ::buffa::OwnedView::decode_with_options(bytes, opts)?,
                    ),
                )
            }
            /// Build from an owned message via an encode → decode round-trip.
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
            /// somehow invalid (should not happen for well-formed messages).
            pub fn from_owned(
                msg: &super::super::CreateGreetingRequest,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    CreateGreetingRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
                )
            }
            /// Borrow the full [`CreateGreetingRequestView`] with its lifetime tied to `&self`.
            #[must_use]
            pub fn view(&self) -> &CreateGreetingRequestView<'_> {
                self.0.reborrow()
            }
            /// Convert to the owned message type.
            #[must_use]
            pub fn to_owned_message(&self) -> super::super::CreateGreetingRequest {
                self.0.to_owned_message()
            }
            /// The underlying bytes buffer.
            #[must_use]
            pub fn bytes(&self) -> &::buffa::bytes::Bytes {
                self.0.bytes()
            }
            /// Consume the handle, returning the underlying bytes buffer.
            #[must_use]
            pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
                self.0.into_bytes()
            }
            /// Field 1: `greeting`
            #[must_use]
            pub fn greeting(
                &self,
            ) -> &::buffa::MessageFieldView<
                super::super::__buffa::view::GreetingView<'_>,
            > {
                &self.0.reborrow().greeting
            }
        }
        impl ::core::convert::From<
            ::buffa::OwnedView<CreateGreetingRequestView<'static>>,
        > for CreateGreetingRequestOwnedView {
            fn from(
                inner: ::buffa::OwnedView<CreateGreetingRequestView<'static>>,
            ) -> Self {
                CreateGreetingRequestOwnedView(inner)
            }
        }
        impl ::core::convert::From<CreateGreetingRequestOwnedView>
        for ::buffa::OwnedView<CreateGreetingRequestView<'static>> {
            fn from(wrapper: CreateGreetingRequestOwnedView) -> Self {
                wrapper.0
            }
        }
        impl ::core::convert::AsRef<
            ::buffa::OwnedView<CreateGreetingRequestView<'static>>,
        > for CreateGreetingRequestOwnedView {
            fn as_ref(&self) -> &::buffa::OwnedView<CreateGreetingRequestView<'static>> {
                &self.0
            }
        }
        impl ::buffa::HasMessageView for super::super::CreateGreetingRequest {
            type View<'a> = CreateGreetingRequestView<'a>;
            type ViewHandle = CreateGreetingRequestOwnedView;
        }
        impl ::serde::Serialize for CreateGreetingRequestOwnedView {
            fn serialize<__S: ::serde::Serializer>(
                &self,
                __s: __S,
            ) -> ::core::result::Result<__S::Ok, __S::Error> {
                ::serde::Serialize::serialize(&self.0, __s)
            }
        }
        #[derive(Clone, Debug, Default)]
        pub struct GetGreetingRequestView<'a> {
            /// Field 1: `name`
            pub name: &'a str,
            pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
        }
        impl<'a> GetGreetingRequestView<'a> {
            /// Decode from `buf`, enforcing a recursion depth limit for nested messages.
            ///
            /// Called by [`::buffa::MessageView::decode_view`] with [`::buffa::RECURSION_LIMIT`]
            /// and by generated sub-message decode arms with `depth - 1`.
            ///
            /// **Not part of the public API.** Named with a leading underscore to
            /// signal that it is for generated-code use only.
            #[doc(hidden)]
            pub fn _decode_depth(
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                let mut view = Self::default();
                view._merge_into_view(buf, depth)?;
                ::core::result::Result::Ok(view)
            }
            /// Merge fields from `buf` into this view (proto merge semantics).
            ///
            /// Repeated fields append; singular fields last-wins; singular
            /// MESSAGE fields merge recursively. Used by sub-message decode
            /// arms when the same field appears multiple times on the wire.
            ///
            /// **Not part of the public API.**
            #[doc(hidden)]
            pub fn _merge_into_view(
                &mut self,
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<(), ::buffa::DecodeError> {
                let _ = depth;
                #[allow(unused_variables)]
                let view = self;
                let mut cur: &'a [u8] = buf;
                while !cur.is_empty() {
                    let before_tag = cur;
                    let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
                    match tag.field_number() {
                        1u32 => {
                            if tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 1u32,
                                    expected: 2u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            view.name = ::buffa::types::borrow_str(&mut cur)?;
                        }
                        _ => {
                            ::buffa::encoding::skip_field_depth(tag, &mut cur, depth)?;
                            let span_len = before_tag.len() - cur.len();
                            view.__buffa_unknown_fields
                                .push_raw(&before_tag[..span_len]);
                        }
                    }
                }
                ::core::result::Result::Ok(())
            }
        }
        impl<'a> ::buffa::MessageView<'a> for GetGreetingRequestView<'a> {
            type Owned = super::super::GetGreetingRequest;
            fn decode_view(
                buf: &'a [u8],
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                Self::_decode_depth(buf, ::buffa::RECURSION_LIMIT)
            }
            fn decode_view_with_limit(
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                Self::_decode_depth(buf, depth)
            }
            fn to_owned_message(&self) -> super::super::GetGreetingRequest {
                self.to_owned_from_source(None)
            }
            #[allow(clippy::useless_conversion, clippy::needless_update)]
            fn to_owned_from_source(
                &self,
                __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
            ) -> super::super::GetGreetingRequest {
                #[allow(unused_imports)]
                use ::buffa::alloc::string::ToString as _;
                let _ = __buffa_src;
                super::super::GetGreetingRequest {
                    name: self.name.to_string(),
                    __buffa_unknown_fields: self
                        .__buffa_unknown_fields
                        .to_owned()
                        .unwrap_or_default()
                        .into(),
                    ..::core::default::Default::default()
                }
            }
        }
        impl<'a> ::buffa::ViewEncode<'a> for GetGreetingRequestView<'a> {
            #[allow(clippy::needless_borrow, clippy::let_and_return)]
            fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
                #[allow(unused_imports)]
                use ::buffa::Enumeration as _;
                let mut size = 0u32;
                if !self.name.is_empty() {
                    size += 1u32 + ::buffa::types::string_encoded_len(&self.name) as u32;
                }
                size += self.__buffa_unknown_fields.encoded_len() as u32;
                size
            }
            #[allow(clippy::needless_borrow)]
            fn write_to(
                &self,
                _cache: &mut ::buffa::SizeCache,
                buf: &mut impl ::buffa::bytes::BufMut,
            ) {
                #[allow(unused_imports)]
                use ::buffa::Enumeration as _;
                if !self.name.is_empty() {
                    ::buffa::encoding::Tag::new(
                            1u32,
                            ::buffa::encoding::WireType::LengthDelimited,
                        )
                        .encode(buf);
                    ::buffa::types::encode_string(&self.name, buf);
                }
                self.__buffa_unknown_fields.write_to(buf);
            }
        }
        /// Serializes this view as protobuf JSON.
        ///
        /// Implicit-presence fields with default values are omitted, `required`
        /// fields are always emitted, explicit-presence (`optional`) fields are
        /// emitted only when set, bytes fields are base64-encoded, and enum
        /// values are their proto name strings.
        ///
        /// This impl uses `serialize_map(None)` because the number of emitted
        /// fields depends on default-omission rules; serializers that require
        /// known map lengths (e.g. `bincode`) will return a runtime error.
        /// Use the owned message type for those formats.
        impl<'__a> ::serde::Serialize for GetGreetingRequestView<'__a> {
            fn serialize<__S: ::serde::Serializer>(
                &self,
                __s: __S,
            ) -> ::core::result::Result<__S::Ok, __S::Error> {
                use ::serde::ser::SerializeMap as _;
                let mut __map = __s.serialize_map(::core::option::Option::None)?;
                if !::buffa::json_helpers::skip_if::is_empty_str(self.name) {
                    __map.serialize_entry("name", self.name)?;
                }
                __map.end()
            }
        }
        impl<'a> ::buffa::MessageName for GetGreetingRequestView<'a> {
            const PACKAGE: &'static str = "golden_path_app.v1";
            const NAME: &'static str = "GetGreetingRequest";
            const FULL_NAME: &'static str = "golden_path_app.v1.GetGreetingRequest";
            const TYPE_URL: &'static str = "type.googleapis.com/golden_path_app.v1.GetGreetingRequest";
        }
        impl<'v> ::buffa::DefaultViewInstance for GetGreetingRequestView<'v> {
            fn default_view_instance<'a>() -> &'a Self
            where
                Self: 'a,
            {
                static VALUE: ::buffa::__private::OnceBox<
                    GetGreetingRequestView<'static>,
                > = ::buffa::__private::OnceBox::new();
                VALUE
                    .get_or_init(|| ::buffa::alloc::boxed::Box::new(
                        <GetGreetingRequestView<'static>>::default(),
                    ))
            }
        }
        impl ::buffa::ViewReborrow for GetGreetingRequestView<'static> {
            type Reborrowed<'b> = GetGreetingRequestView<'b>;
            fn reborrow<'b>(this: &'b Self) -> &'b Self::Reborrowed<'b> {
                this
            }
        }
        /** Self-contained, `'static` owned view of a `GetGreetingRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`GetGreetingRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`GetGreetingRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
        #[derive(Clone, Debug)]
        pub struct GetGreetingRequestOwnedView(
            ::buffa::OwnedView<GetGreetingRequestView<'static>>,
        );
        impl GetGreetingRequestOwnedView {
            /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
            ///
            /// The view borrows directly from the buffer's data; the buffer is
            /// retained inside the returned handle.
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
            /// protobuf data.
            pub fn decode(
                bytes: ::buffa::bytes::Bytes,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    GetGreetingRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
                )
            }
            /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
            /// max message size).
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
            /// exceeds the configured limits.
            pub fn decode_with_options(
                bytes: ::buffa::bytes::Bytes,
                opts: &::buffa::DecodeOptions,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    GetGreetingRequestOwnedView(
                        ::buffa::OwnedView::decode_with_options(bytes, opts)?,
                    ),
                )
            }
            /// Build from an owned message via an encode → decode round-trip.
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
            /// somehow invalid (should not happen for well-formed messages).
            pub fn from_owned(
                msg: &super::super::GetGreetingRequest,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    GetGreetingRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
                )
            }
            /// Borrow the full [`GetGreetingRequestView`] with its lifetime tied to `&self`.
            #[must_use]
            pub fn view(&self) -> &GetGreetingRequestView<'_> {
                self.0.reborrow()
            }
            /// Convert to the owned message type.
            #[must_use]
            pub fn to_owned_message(&self) -> super::super::GetGreetingRequest {
                self.0.to_owned_message()
            }
            /// The underlying bytes buffer.
            #[must_use]
            pub fn bytes(&self) -> &::buffa::bytes::Bytes {
                self.0.bytes()
            }
            /// Consume the handle, returning the underlying bytes buffer.
            #[must_use]
            pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
                self.0.into_bytes()
            }
            /// Field 1: `name`
            #[must_use]
            pub fn name(&self) -> &'_ str {
                self.0.reborrow().name
            }
        }
        impl ::core::convert::From<::buffa::OwnedView<GetGreetingRequestView<'static>>>
        for GetGreetingRequestOwnedView {
            fn from(inner: ::buffa::OwnedView<GetGreetingRequestView<'static>>) -> Self {
                GetGreetingRequestOwnedView(inner)
            }
        }
        impl ::core::convert::From<GetGreetingRequestOwnedView>
        for ::buffa::OwnedView<GetGreetingRequestView<'static>> {
            fn from(wrapper: GetGreetingRequestOwnedView) -> Self {
                wrapper.0
            }
        }
        impl ::core::convert::AsRef<::buffa::OwnedView<GetGreetingRequestView<'static>>>
        for GetGreetingRequestOwnedView {
            fn as_ref(&self) -> &::buffa::OwnedView<GetGreetingRequestView<'static>> {
                &self.0
            }
        }
        impl ::buffa::HasMessageView for super::super::GetGreetingRequest {
            type View<'a> = GetGreetingRequestView<'a>;
            type ViewHandle = GetGreetingRequestOwnedView;
        }
        impl ::serde::Serialize for GetGreetingRequestOwnedView {
            fn serialize<__S: ::serde::Serializer>(
                &self,
                __s: __S,
            ) -> ::core::result::Result<__S::Ok, __S::Error> {
                ::serde::Serialize::serialize(&self.0, __s)
            }
        }
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__GREETING_JSON_ANY);
        reg.register_json_any(super::__CREATE_GREETING_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GET_GREETING_REQUEST_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::GreetingView;
#[doc(inline)]
pub use self::__buffa::view::GreetingOwnedView;
#[doc(inline)]
pub use self::__buffa::view::CreateGreetingRequestView;
#[doc(inline)]
pub use self::__buffa::view::CreateGreetingRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::GetGreetingRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetGreetingRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::register_types;
